### ISSUE TITLE
Pre-211028 Raspi 3 updated to 231114 does not display anything.

### ISSUE THREAD

**Issue by hvij1228** [monome/norns-image#104]
Is OS ver. 231114 compatible with pre-211028 shields (raspbi 3)? I had to do a clean install to OS ver. 220306 and when I updated to 231114 my norns shield when restarted was blank but was generating the boot-up soundbyte. My norns unit works as expected otherwise. I'm just unable to run some of the scripts when installed (error: load fail).

**Comment by tehn** [comment]
you update failed. do a manual update: https://llllllll.co/t/norns-update-231114/64915/22?u=tehn
