### ISSUE TITLE
audio glitches with RT kernel and moderate CPU load

### ISSUE THREAD

**Issue by catfact** [monome/norns-image#38]
in the process of trying to squeeze out more performance for MLR, i belatedly realized that the audio glitches we experience due to CPU load are not typically symptomatic of jack/ALSA buffer underruns.

- these are kind of drawn-out micro-stutters that start being apparent when scsynth usage approaches ~50% of one CPU in `top`
- `top` also shows that the CPU load distribution is pretty reasonable, and using `tasksel` to forcefully redistribute processes has no effect.
- no xruns are reported by jack in the output of scsynth.

so, i dug a little more and gathered a few more data points:

- glitchiness seemed unaffected by ALSA period size (default 128, tried up to 1024.)

- ran the system using the CM3's default `kernel7.img` instead of the realtime kernel. this has no support for `monome-snd` so used a USB audio interface. no glitches! our heaviest use case is reading+writing with all four voices in MLR, plus reverb and compression; scsynth uses ~60% CPU with no audible ill effects.

- tried setting `elevator=deadline` in /boot/commandline.txt, this seems to have no effect with the default kernel and makes the artifacts in the RT kernel noticeably worse. 

- USB soundcard on the RT kernel is just as bad, which seems to rule out a `monome-snd` driver problem.

so i think we should try without the RT patches. we can't do everything we want using <50% of one core for scsynth.

**Comment by simonvanderveldt** [comment]
@catfact Since we're now using a regular/non-RT kernel, do you think we can close this?

**Comment by okyeron** [comment]
Question regarding realtime kernel - if building from source on Raspberry Pi, does this refer to 

`Kernel Features —> Preemption Model (Preemptible Kernel (Low-Latency Desktop))`

and would it be recommended to leave it as default instead?

**Comment by artfwo** [comment]
@okyeron, no, this refers to CONFIG_PREEMPT_RT, see https://rt.wiki.kernel.org/index.php/Main_Page for details.

for norns we're currently not using the RT patchset and enabling preemption using CONFIG_PREEMPT, which is the same as the "Low-Latency Desktop" option you mentioned.
