### ISSUE TITLE
avahi-daemon consistently stops publishing services

### ISSUE THREAD

**Issue by artfwo** [monome/norns-image#42]
Both `norns.local` hostname and matron's `_osc._udp` service are unpublished in an unknown timeframe after starting wifi.

**Comment by artfwo** [comment]
fixed with the driver update.

**Comment by tehn** [comment]
do I need to add apt update to the 2.1.0 update script?

**Comment by artfwo** [comment]
@tehn no, i believe the problem was caused by the old wifi driver, not reproducible anymore.
