### ISSUE TITLE
hard dependencies for systemd units

### ISSUE THREAD

**Issue by artfwo** [monome/norns-image#44]
systemd units should have explicit (Requires) dependencies as illustrated below:

- norns-init
  - norns-jack (also require sound.target)
    - norns-crone
  - norns-matron (also require sockets.target)
  - norns-maiden

`norns.target` should explicitly require all of the above.

**Comment by simonvanderveldt** [comment]
@artfwo I think this is all done at the moment, right?

**Comment by artfwo** [comment]
@simonvanderveldt yes, looks like it!
