### ISSUE TITLE
Kernel download url comes back AccessDenied

### ISSUE THREAD

**Issue by okyeron** [monome/norns-image#51]
From the build readme (build-dev-image.md), the kernel download url here comes back with "403 Forbidden"

wget https://monome.nyc3.digitaloceanspaces.com/kernel-4.9.59-rt52-0.0.4.tar.gz

**Comment by tehn** [comment]
the kernel has changed and there isn't an uploaded copy.

compile the kernel yourself for now, it's straightforward: https://github.com/monome/linux

run build-kernel.sh
