### ISSUE TITLE
Using other DAC's outputs on Raspberry Pi

### ISSUE THREAD

**Issue by okyeron** [monome/norns-image#53]
I'm using a WM8731 DAC and would like to make use of the built-in headphone amp in that chip. Norns hardware seems to have a separate chip handling the headphone output (and uses some i2c code to change those values).

I can't seem to find where norns is sending alsa/jack volume change commands for the main outputs. I figured this might be a good place to look for implementing headphone controls with the WM8731.

Any suggestions?

**Comment by tehn** [comment]
we don't actually do any ALSA control within matron. the headphone gain is controlled via i2c (trace the commands to find the inner workings, but it doesn't seem to apply to your case).

if you want to issue ALSA commands, just use `os.execute` from within lua and that should work fine.

but generally other DACs and sound cards should work fine out of the box provided you set up jack correctly, so i'm going to close this. feel free to continue to comment and i'll attempt to answer questions.

**Comment by okyeron** [comment]
Thanks - further digging led me to the same conclusion regarding ALSA

FWIW - the WM8731 DAC works great for audio output and input - output levels are controlled OK with the volume controls. However, the input volume levels can't be controlled from the norns software as it looks like that's happening in i2c.c .

I'll keep digging.

**Comment by tehn** [comment]
the input gains are obsolete-- the hardware was removed. so that i2c code will also go away.

**Comment by okyeron** [comment]
Understood. Thanks!
